### ISSUE TITLE
Lighter container to use in IRIS-CI

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolibgpu#125]
there is a developer heavyweight container in IRIS CI at the moment. Try the base one instead which is more lightweight / faster.

**Comment by yousefmoazzam** [comment]
When building container images for httomo devcontainers, I've used as a base image a [micromamba container image with CUDA support](https://hub.docker.com/r/mambaorg/micromamba/tags?page=&page_size=&ordering=&name=cuda) which is decently smaller in size (~100MB) compared to the nvidia CUDA developer container images (~3GB). May or may not work, perhaps there will be some peculiarities when using it on IRIS regarding permissions within the container, but I'm happy to give it a go and see what happens.

**Comment by yousefmoazzam** [comment]
It's worth noting that in the successful runs of that workflow (like this one https://github.com/DiamondLightSource/httomolibgpu/actions/runs/9208468331/job/25330732593), the initialisation of the container took ~1 min, whereas the creation of the conda env took ~8 mins. From that, I would naively guess that the slowness of the workflow is something specific to the step/github action doing the conda env creation, rather than something with the container image itself, but I'm not sure.

**Comment by yousefmoazzam** [comment]
Mmm, given how #129 is solely targeting the conda env creation and was able to speed up the workflow by ~4 mins by reducing the time taken to create the conda env, I think that the container image being a large nvidia CUDA developer isn't a major factor in the slowness.

The container initialisation consistently takes ~1 min, whereas the conda env creation takes at least several minutes.
