### ISSUE TITLE
Tomopy methods to port for acceleration

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolibgpu#22]
We need to port:

1.  _remove_all_stripe_, _remove_large_stripe_ and _remove_dead_stripe_ from [here](https://github.com/tomopy/tomopy/blob/master/source/tomopy/prep/stripe.py)
2. retrieve_phase from [here](https://github.com/tomopy/tomopy/blob/master/source/tomopy/prep/phase.py). This is so-called [Paganin filter](https://github.com/DiamondLightSource/httomolib/blob/34c01ffbdf2f53eea5dc17aecd3e4b1051b1cbc8/src/httomolib/prep/phase.py#L128) but we need to make it consistent with TomoPy implementation
3. Distortion correction as in [here](https://github.com/tomopy/tomopy/blob/1cb9411f6c17ca3e6eba72a2e7b67ed4f0e77498/source/tomopy/prep/alignment.py#L912)

**Comment by yousefmoazzam** [comment]
Re: item 3 in the list.

An alternative distortion correction implementation has been added in 050ded9.

It is based on the implementation in Discorpy https://github.com/DiamondLightSource/discorpy/blob/67743842b60bf5dd45b21b8460e369d4a5e94d67/discorpy/post/postprocessing.py#L111-L148 rather than TomoPy https://github.com/tomopy/tomopy/blob/c236a2969074f5fc70189fb5545f0a165924f916/source/tomopy/prep/alignment.py#L950-L981.

This is because they are actually almost identical to each another, except that the Discorpy version is slightly more flexible by allowing users to pass the `order`  and `mode` parameters through to the `map_coordinates()` function from NumPy https://github.com/DiamondLightSource/discorpy/blob/67743842b60bf5dd45b21b8460e369d4a5e94d67/discorpy/post/postprocessing.py#L147.

**Comment by yousefmoazzam** [comment]
It's not urgently needed to be ready for the GPU contractor's start date, but as a note, it was also previously discussed that the methods relating to 360 sinograms would be useful to make GPU ports of sometime, namely:
- Conversion of a 360 degree sinogram to a 180 degree sinogram (from TomoPy): https://github.com/tomopy/tomopy/blob/master/source/tomopy/misc/morph.py#L314-L356
- Finding the CoR of a 360 sinogram (from algotom): https://github.com/algotom/algotom/blob/96ec59e4ae49d937ae26be2e63aa6d0ec55da3a6/algotom/prep/calculation.py#L599-L649
